on:
  issues:
    types: labeled
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  issues: write

name: Label and close issues with no recent activity

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEEDS_ATTENTION_LABEL: "Needs attention"
  NEEDS_AUTHOR_FEEDBACK_LABEL: "Needs author feedback"
  NO_RECENT_ACTIVITY_LABEL: "No recent activity"
  NO_RECENT_ACTIVITY_DURATION: "00:00:01"
  NO_RECENT_ACTIVITY_DURATION_CLOSE: "00:00:01"
  ORG_NAME: "baywet"
  REPO_NAME: "OASAutomations"
  NO_RECENT_ACTIVITY_COMMENT: "This issue has been labeled because there has been no recent activity. It will be closed if no further activity occurs within 1 day."


jobs:
  run:
    runs-on: ubuntu-latest
    name: Label issues with no recent activity
    steps:
      - uses: actions/checkout@v4
      - run: scripts/label-no-recent.ps1
        shell: pwsh
      - run: scripts/close-no-recent.ps1
        shell: pwsh
